### ISSUE TITLE
w.r.t synthetic generation part

### ISSUE THREAD

**Issue by vingving** [cszhilu1998/BracketIRE#2]
Thank you for sharing your work! I think it is a great approach to solve multi-exposure problems!
Could you also share your synthetic data generation part to the github repo?

**Comment by cszhilu1998** [comment]
We consider making this part public after the paper is accepted. 
In addition, we will soon make the dataset and code of the real-world experiments public.

**Comment by cszhilu1998** [comment]
> Thank you for sharing your work! I think it is a great approach to solve multi-exposure problems! Could you also share your synthetic data generation part to the github repo?

Hi, the paper has been accepted by ICLR 2025. The code for generating synthetic dataset have been released in [syn_data_gen](https://github.com/cszhilu1998/BracketIRE/blob/master/syn_data_gen) folder.
