### ISSUE TITLE
About the install issue

### ISSUE THREAD

**Issue by JacksonWang** [cszhilu1998/BracketIRE#3]
Hi, I just get this project. 
And when I want to build a virtual env try to build my own testing, I face 2 problems. 

First is the requirements colour_demosaicing==0.2.5, and it need python version >=3.9,<3.13, even the oldest 0.2.3 requires python version >=3.9,<3.12. If my env is python 3.8, can I install colour_demosaicing==0.2.2 instand?
Second, the requirements duplicate tensorboardX==2.6.2.2.

**Comment by JacksonWang** [comment]
Just get, the requirements duplicate Pillow with different version

**Comment by cszhilu1998** [comment]
For the first problem, we recommend that you change the python version to 3.9. 
For the second problem, we have updated [requirements.txt](https://github.com/cszhilu1998/BracketIRE/blob/master/requirements.txt).
