### ISSUE TITLE
about Synthetic dataset

### ISSUE THREAD

**Issue by Ethean** [cszhilu1998/BracketIRE#4]
Thank you for the awosome work. I'm studying this topic and it's hard for me to get real-world data. So I want to know how to simulate the Synthetic training data. Do you have any plan to share the scripts used to generate Synthetic data ?

**Comment by cszhilu1998** [comment]
Thank you for your recognition. We consider making this part public after the paper is accepted.

**Comment by cszhilu1998** [comment]
> Thank you for the awosome work. I'm studying this topic and it's hard for me to get real-world data. So I want to know how to simulate the Synthetic training data. Do you have any plan to share the scripts used to generate Synthetic data ?

Hi, the paper has been accepted by ICLR 2025. The code for generating synthetic dataset have been released in [syn_data_gen](https://github.com/cszhilu1998/BracketIRE/blob/master/syn_data_gen) folder.
